<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async and await</title>
</head>
<body>
    <script>
      //There’s a special syntax to work with promises in a more comfortable fashion, called “async/await”.

//The word “async” before a function means one simple thing: a function always returns a promise. 
//Other values are wrapped in a resolved promise automatically.

//The keyword await makes JavaScript wait until that promise settles and returns its result.



async function f() {

let promise = new Promise((resolve, reject) => {
  setTimeout(() => resolve("done!"), 1000)
});

let result = await promise; // wait until the promise resolves (*)

alert(result); // "done!"
}

f();


//The function execution “pauses” at the line (*) and resumes when the promise settles, 
//with result becoming its result. So the code above shows “done!” in one second.
// Let’s emphasize: await literally suspends the function execution until the promise settles,
//  and then resumes it with the promise result. That doesn’t cost any CPU resources, 
//  because the JavaScript engine can do other jobs in the meantime: execute other scripts, handle events, etc
// It’s just a more elegant syntax of getting the promise result than promise.then. And, it’s easier to read and write.






//Can’t use await in regular functions:
function f() {
  let promise = Promise.resolve(1);
  let result = await promise; // Syntax error
}




//If a promise resolves normally, then await promise returns the result. But in the case of a rejection, it throws the error, just as if there were a throw statement at that line.
async function f() {
  await Promise.reject(new Error("Whoops!"));
}









//catcah errror using try and catch :
async function f() {

try {
  let response = await fetch('http://no-such-url');
} catch(err) {
  alert(err); // TypeError: failed to fetch
}
}

f();




//In the case of an error, the control jumps to the catch block. We can also wrap multiple lines:
async function f() {

try {
  let response = await fetch('/no-user-here');
  let user = await response.json();
} catch(err) {
  // catches errors both in fetch and response.json
  alert(err);
}
}

f();




//When we need to wait for multiple promises, we can wrap them in Promise.all and then await:
// wait for the array of results
// let results = await Promise.all([
//   fetch(url1),
//   fetch(url2),
//   ...
// ]);






// Summary
// The async keyword before a function has two effects:

// Makes it always return a promise.
// Allows await to be used in it.
// The await keyword before a promise makes JavaScript wait until that promise settles, and then:

// If it’s an error, an exception is generated — same as if throw error were called at that very place.
// Otherwise, it returns the result.
// Together they provide a great framework to write asynchronous code that is easy to both read and write.

// With async/await we rarely need to write promise.then/catch, 
// but we still shouldn’t forget that they are based on promises, 
// because sometimes (e.g. in the outermost scope) we have to use these methods. 
// Also Promise.all is nice when we are waiting for many tasks simultaneously.













    </script>
</body>
</html>